collections:
  authors:
    output: true

include: ['_pages']

baseurl: /web

url: "https://czechultimate.com"

paginate: 12
paginate_path: "/archiv/page:num/"

plugins:
   - jekyll-sitemap
   - jekyll-seo-tag
   - jekyll-paginate

exclude:
- README.md
- Gemfile
- Gemfile.lock
- semantic.json
- package-lock.json
- node_modules
- docker-compose.yml
